"""update product table

Revision ID: 35e1c8e29432
Revises: 76bbc257629a
Create Date: 2022-11-04 12:44:12.191354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e1c8e29432'
down_revision = '76bbc257629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('image_2', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addproduct', 'image_2')
    # ### end Alembic commands ###
