"""update in image

Revision ID: 76bbc257629a
Revises: c5fb0072e395
Create Date: 2022-11-04 11:14:23.945304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76bbc257629a'
down_revision = 'c5fb0072e395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addproduct', 'image_3')
    op.drop_column('addproduct', 'image_5')
    op.drop_column('addproduct', 'image_4')
    op.drop_column('addproduct', 'image_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('image_2', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('addproduct', sa.Column('image_4', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('addproduct', sa.Column('image_5', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('addproduct', sa.Column('image_3', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
