"""update

Revision ID: 8a9ed089e791
Revises: e01ce9597311
Create Date: 2022-11-04 12:58:39.724442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9ed089e791'
down_revision = 'e01ce9597311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('images', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addproduct', 'images')
    # ### end Alembic commands ###
