"""mini update

Revision ID: b81138facc12
Revises: b9a260c072eb
Create Date: 2022-11-04 15:10:53.834743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b81138facc12'
down_revision = 'b9a260c072eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_photo')
    op.alter_column('addproduct', 'image_1',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addproduct', 'image_1',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.create_table('products_photo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
