"""update

Revision ID: b9a260c072eb
Revises: 8a9ed089e791
Create Date: 2022-11-04 13:13:58.926168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a260c072eb'
down_revision = '8a9ed089e791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('image_2', sa.String(length=150), nullable=True))
    op.add_column('addproduct', sa.Column('image_3', sa.String(length=150), nullable=True))
    op.drop_column('addproduct', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('images', sa.BLOB(), nullable=True))
    op.drop_column('addproduct', 'image_3')
    op.drop_column('addproduct', 'image_2')
    # ### end Alembic commands ###
