"""again update

Revision ID: e01ce9597311
Revises: 35e1c8e29432
Create Date: 2022-11-04 12:48:57.608565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01ce9597311'
down_revision = '35e1c8e29432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addproduct', 'image_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addproduct', sa.Column('image_2', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
